# Imersão de Dados 4 - Alura - Desafios Dia 5

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

pd.set_option("display.precision", 2)
pd.set_option("display.float_format", lambda x: "%.2f" % x)
sns.set()

data_censo = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/dados_vendas_censo.csv")
data_censo = data_censo[["Rua", "Bairro", "Cidade", "Metragem", "Quartos", "Banheiros", "Vagas",
       "Valor_anuncio", "Valor_mm", "Valor_m2", "latitude", "longitude", "Situacao_setor", "V001",
       "V002", "V003", "V004", "V005", "V006", "V007", "V008", "V009", "V010",
       "V011", "V012"]].dropna()
data_censo

Rua              Bairro     Cidade  Metragem  \
0              Avenida Itacira, 255    Planalto Paulista  São Paulo      1000   
1     Rua Aurelia Perez Alvarez, 42   Jardim dos Estados  São Paulo       496   
2                    Rua Alba Valdez     Jardim Reimberg  São Paulo       125   
3           Rua Tobias Barreto, 195                Mooca  São Paulo       100   
4                    Rua Graham Bell         Santo Amaro  São Paulo       440   
...                              ...                 ...        ...       ...   
5599              Rua Pedro Teixeira        Vila Olímpia  São Paulo       157   
5600                   Avenida Odila   Planalto Paulista  São Paulo       267   
5601                      Rua Tapuçu          Vila Sofia  São Paulo        95   
5603               Rua Estero Belaco       Vila da Saúde  São Paulo       205   
5604      Rua Barão de Tramandaí, 0          Vila Alpina  São Paulo       122   

      Quartos  Banheiros  Vagas  Valor_anuncio  Valor_mm  Valor_m2  ...  V003  \
0           4          8      6     7000000.00      7.00   7000.00  ...  2.66   
1           4          4      4     3700000.00      3.70   7459.68  ...  3.13   
2           4          3      2      380000.00      0.38   3040.00  ...  3.47   
3           3          2      2      540000.00      0.54   5400.00  ...  3.00   
4           4          4      6     1980000.00      1.98   4500.00  ...  3.51   
...       ...        ...    ...            ...       ...       ...  ...   ...   
5599        3          2      2      960000.00      0.96   6114.65  ...  2.17   
5600        3          6      4     1500000.00      1.50   5617.98  ...  2.81   
5601        2          2      2      665000.00      0.67   7000.00  ...  2.99   
5603        3          3      6     1050000.00      1.05   5121.95  ...  2.75   
5604        3          2      2      270000.00      0.27   2213.11  ...  2.97   

      V004    V005        V006    V007        V008    V009        V010  \
0     2.04 3158.96 22210644.93 5570.65 25770816.97 2096.19 13029851.56   
1     1.96 7600.44 36778930.17 7890.53 35886906.64 4149.00 26760682.90   
2     3.06  805.13   769188.78 1011.75   757433.42  518.77   426672.78   
3     1.99 2338.05  7826370.15 2447.89  7925839.76 1543.29  4646566.16   
4     2.31 1026.36   272168.67 1143.96   167733.64  735.67   367088.08   
...    ...     ...         ...     ...         ...     ...         ...   
5599  1.27 5054.58 33245189.73 5231.93 33485189.78 3649.06 26562232.53   
5600  1.60 4249.33 24499871.44 5180.14 25047413.33 2618.76 17705032.31   
5601  1.81 2425.09  6878872.25 2543.80  6913867.79 1561.58  4261814.01   
5603  1.50 5650.20 20344622.14 5750.84 20127679.27 3459.68 16021825.60   
5604  1.75 1244.10  1353001.23 1364.89  1319336.96  895.93   988708.13   

        V011        V012  
0    3930.35 17241576.74  
1    6063.92 27502674.90  
2     858.51   414378.88  
3    1909.04  5050712.69  
4    1086.94   159622.46  
...      ...         ...  
5599 4551.66 29032823.35  
5600 3977.93 21495997.85  
5601 2062.09  4596759.57  
5603 4362.79 16264378.33  
5604 1226.86   947807.31  

[5308 rows x 25 columns]

## 1 - Add the "real" price of the property's m².

## 2 - Test other regression models.

In [ ]:
from sklearn.model_selection import train_test_split

X = data_censo[["Metragem"]]
Y = data_censo["Valor_anuncio"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=54)

In [ ]:
Y_test

5009   3100000.00
4183   2500000.00
792    3350000.00
1755   5500000.00
5114    870000.00
          ...    
1655    905000.00
958    2700000.00
2387    940000.00
3068    720000.00
2968   1500000.00
Name: Valor_anuncio, Length: 1327, dtype: float64

### Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

In [ ]:
lr.fit(X_train, Y_train)

LinearRegression()

In [ ]:
Y_predict_test = lr.predict(X_test)
Y_predict_test

array([2846638.80089075, 2306582.72960118, 1756525.61995439, ...,
       1116459.16509267,  366381.28830159, 2166568.19260018])

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score
mean_absolute_error(Y_test, Y_predict_test)

1560602.211792463

### SVM Regression

In [ ]:
from sklearn import svm

regr = svm.SVR()

In [ ]:
regr.fit(X, Y)

SVR()

In [ ]:
Y_predict_test = regr.predict(X_test)
Y_predict_test

array([1600568.67336444, 1600397.3151492 , 1600234.52067604, ...,
       1600069.97325586, 1599923.21538806, 1600354.43710395])

In [ ]:
mean_absolute_error(Y_test, Y_predict_test)

1837173.0314215745

### Decision Tree Regression

In [27]:
from sklearn import tree

clf = tree.DecisionTreeRegressor()

In [28]:
clf = clf.fit(X, Y)

In [29]:
Y_predict_test = clf.predict(X_test)
Y_predict_test

array([2552000.        , 1985322.58064516, 1597289.44736842, ...,
       1269600.        ,  647000.        , 1760909.09090909])

In [30]:
mean_absolute_error(Y_test, Y_predict_test)

944171.7012429505

## 3 - Create a baseline model with the original features.

IBGE data do not affect the prediction of any of the models in any way.

In [31]:
data = data_censo[["Rua", "Bairro", "Cidade", "Metragem", "Quartos", "Banheiros", "Vagas",
       "Valor_anuncio", "Valor_mm", "Valor_m2"]].dropna()
data

Rua              Bairro     Cidade  Metragem  \
0              Avenida Itacira, 255    Planalto Paulista  São Paulo      1000   
1     Rua Aurelia Perez Alvarez, 42   Jardim dos Estados  São Paulo       496   
2                    Rua Alba Valdez     Jardim Reimberg  São Paulo       125   
3           Rua Tobias Barreto, 195                Mooca  São Paulo       100   
4                    Rua Graham Bell         Santo Amaro  São Paulo       440   
...                              ...                 ...        ...       ...   
5599              Rua Pedro Teixeira        Vila Olímpia  São Paulo       157   
5600                   Avenida Odila   Planalto Paulista  São Paulo       267   
5601                      Rua Tapuçu          Vila Sofia  São Paulo        95   
5603               Rua Estero Belaco       Vila da Saúde  São Paulo       205   
5604      Rua Barão de Tramandaí, 0          Vila Alpina  São Paulo       122   

      Quartos  Banheiros  Vagas  Valor_anuncio  Valor_mm  Valor_m2  
0           4          8      6     7000000.00      7.00   7000.00  
1           4          4      4     3700000.00      3.70   7459.68  
2           4          3      2      380000.00      0.38   3040.00  
3           3          2      2      540000.00      0.54   5400.00  
4           4          4      6     1980000.00      1.98   4500.00  
...       ...        ...    ...            ...       ...       ...  
5599        3          2      2      960000.00      0.96   6114.65  
5600        3          6      4     1500000.00      1.50   5617.98  
5601        2          2      2      665000.00      0.67   7000.00  
5603        3          3      6     1050000.00      1.05   5121.95  
5604        3          2      2      270000.00      0.27   2213.11  

[5308 rows x 10 columns]

In [39]:
X = data[["Metragem"]]
Y = data["Valor_anuncio"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=54)

### Linear Regression

In [40]:
lr = LinearRegression()
lr.fit(X_train, Y_train)
Y_predict_test = lr.predict(X_test)
Y_predict_test

array([2846638.80089075, 2306582.72960118, 1756525.61995439, ...,
       1116459.16509267,  366381.28830159, 2166568.19260018])

In [41]:
mean_absolute_error(Y_test, Y_predict_test)

1560602.211792463

### SVM Regression

In [43]:
regr = svm.SVR()
regr.fit(X, Y)
Y_predict_test = regr.predict(X_test)
Y_predict_test

array([1600568.67336444, 1600397.3151492 , 1600234.52067604, ...,
       1600069.97325586, 1599923.21538806, 1600354.43710395])

In [44]:
mean_absolute_error(Y_test, Y_predict_test)

1837173.0314215745

### Decision Tree Regression

In [45]:
clf = tree.DecisionTreeRegressor()
clf = clf.fit(X, Y)
Y_predict_test = clf.predict(X_test)
Y_predict_test

array([2552000.        , 1985322.58064516, 1597289.44736842, ...,
       1269600.        ,  647000.        , 1760909.09090909])

In [46]:
mean_absolute_error(Y_test, Y_predict_test)

944171.7012429505

## 4 - Adjust more the data and create new variables.

## 5 - Test the predictions for real cases.

## 6 - Create a project with the results of the Immersion and post it on social networks showing the work done. Remember to tag @AluraOnline and use the hashtags \#ImersãoDados and \#ImersãoDados4.